/* Auto-generated by scripts/gen_mesh_l2_data.py — do not edit. */
#ifndef MESH_L2_DATA_H
#define MESH_L2_DATA_H

#include <stdint.h>

#define MESH_L2_NUM_PARTITIONS 4U
#define MESH_L2_PARTITION_SIZE_BYTES 32768U
#define MESH_L2_PARTITION_SPAN_BYTES 131072U
#define MESH_L2_FLOATS_PER_PARTITION 8192U
#define MESH_L2_NUM_GRANULES 512U
#define MESH_L2_FLOATS_PER_GRANULE 16U
#define MESH_L2_GRANULE_STRIDE_BYTES 256U
#define MESH_L2_REMOTE_ACCESS_STRIDE 8U
#define MESH_L2_BANK_SELECT_BIT_START 6U
#define MESH_L2_BANK_SELECT_BIT_END 7U

static inline uint64_t mesh_l2_elem_byte_offset(uint32_t elem_index) {
  const uint32_t g = elem_index >> 4;
  const uint32_t f = elem_index & 15u;
  return (uint64_t)g * 256u + (uint64_t)f * 4u;
}

static const uint64_t mesh_l2_partition_base[4] = {
  0ull,
  131136ull,
  262272ull,
  393408ull
};

static const uint32_t mesh_l2_partition_home_core[4] = {
  0u,
  1u,
  2u,
  3u
};

static const uint32_t mesh_l2_partition_home_bank[4] = {
  0u,
  1u,
  2u,
  3u
};

static const uint32_t mesh_l2_partition_remote_core[4] = {
  2u,
  3u,
  0u,
  1u
};

#endif /* MESH_L2_DATA_H */
