#!/usr/bin/env python3
"""
Generate mesh_l2_data.h for the mesh_l2_affinity regression.

Partitions are bank-confined: every element address keeps the same
L2 bank-select bits (default geometry: bits 6-7). Elements use 256-byte
granules with 16 floats in the low 64 bytes (stride 256 preserves bank).
"""

from __future__ import annotations

import argparse
import math
import os
from typing import List, TextIO


NUM_PARTITIONS = 4
# Dense working set per partition (bytes touched by the kernel).
PARTITION_SIZE_BYTES = 32768  # 32 KiB -> 8192 floats
REMOTE_ACCESS_STRIDE = 8
FLOATS_PER_GRANULE = 16
GRANULE_STRIDE_BYTES = 256  # 2^(bank_select_end+1); keeps bits 6-7 fixed


def log2ceil(x: int) -> int:
    if x <= 1:
        return 0
    return int(math.ceil(math.log2(x)))


def bank_select_bits(
    *,
    cache_size: int,
    line_size: int,
    word_size: int,
    num_ways: int,
    num_banks: int,
) -> tuple[int, int]:
    """Mirror sim/simx/cache_sim.cpp params_t bank bit positions (byte addresses)."""
    c = log2ceil(cache_size)
    lg_l = log2ceil(line_size)
    lg_w = log2ceil(word_size)
    lg_a = log2ceil(num_ways)
    lg_b = log2ceil(num_banks)
    offset_bits = lg_l - lg_w
    index_bits = c - (lg_l + lg_a + lg_b)
    assert offset_bits >= 0 and index_bits >= 0
    word_start = lg_w
    word_end = word_start + offset_bits - 1
    bank_start = 1 + word_end
    bank_end = bank_start + lg_b - 1
    return bank_start, bank_end


def floats_per_partition() -> int:
    return PARTITION_SIZE_BYTES // 4


def num_granules() -> int:
    n = floats_per_partition()
    assert n % FLOATS_PER_GRANULE == 0
    return n // FLOATS_PER_GRANULE


def partition_span_bytes() -> int:
    return num_granules() * GRANULE_STRIDE_BYTES


def elem_byte_offset(elem_index: int) -> int:
    g = elem_index // FLOATS_PER_GRANULE
    f = elem_index % FLOATS_PER_GRANULE
    return g * GRANULE_STRIDE_BYTES + f * 4


def partition_base(bank_id: int, bank_start: int, part_index: int) -> int:
    """Non-overlapping sparse bases: bank in bits 6-7, set block in bits 8+."""
    return (bank_id << bank_start) | (part_index * num_granules() << (bank_start + log2ceil(4)))


def addr_bank_id(byte_addr: int, bank_start: int) -> int:
    lg_b = log2ceil(4)
    return (byte_addr >> bank_start) & ((1 << lg_b) - 1)


def _emit_u32_array(fp: TextIO, name: str, values: List[int]) -> None:
    fp.write(f"static const uint32_t {name}[{len(values)}] = {{\n")
    for i, v in enumerate(values):
        sep = ",\n" if i + 1 < len(values) else "\n"
        fp.write(f"  {v}u{sep}")
    fp.write("};\n\n")


def _emit_u64_array(fp: TextIO, name: str, values: List[int]) -> None:
    fp.write(f"static const uint64_t {name}[{len(values)}] = {{\n")
    for i, v in enumerate(values):
        sep = ",\n" if i + 1 < len(values) else "\n"
        fp.write(f"  {v}ull{sep}")
    fp.write("};\n\n")


def verify_partition_layout(bank_start: int) -> None:
    span = partition_span_bytes()
    bases = [partition_base(i, bank_start, i) for i in range(NUM_PARTITIONS)]
    nfloats = floats_per_partition()
    for p, base in enumerate(bases):
        assert addr_bank_id(base, bank_start) == p
        for i in (0, 1, nfloats - 1, nfloats // 2):
            for byte_addr in (base + elem_byte_offset(i),):
                assert addr_bank_id(byte_addr, bank_start) == p, (
                    f"part{p} elem{i} bank {addr_bank_id(byte_addr, bank_start)}"
                )
        end = base + span
        for q, other in enumerate(bases):
            if q == p:
                continue
            other_end = other + span
            assert end <= other or other_end <= base, (
                f"part{p} [{base},{end}) overlaps part{q} [{other},{other_end})"
            )


def write_header(path: str) -> None:
    bank_start, bank_end = bank_select_bits(
        cache_size=1048576,
        line_size=64,
        word_size=64,
        num_ways=8,
        num_banks=4,
    )
    verify_partition_layout(bank_start)

    span = partition_span_bytes()
    nfloats = floats_per_partition()
    ngran = num_granules()

    partition_base_addrs: List[int] = []
    partition_home_core: List[int] = []
    partition_home_bank: List[int] = []
    partition_remote_core: List[int] = []

    for i in range(NUM_PARTITIONS):
        base = partition_base(i, bank_start, i)
        partition_base_addrs.append(base)
        partition_home_core.append(i)
        partition_home_bank.append(i)
        partition_remote_core.append((i + 2) % NUM_PARTITIONS)

    with open(path, "w", encoding="utf-8") as fp:
        fp.write("/* Auto-generated by scripts/gen_mesh_l2_data.py — do not edit. */\n")
        fp.write("#ifndef MESH_L2_DATA_H\n#define MESH_L2_DATA_H\n\n")
        fp.write("#include <stdint.h>\n\n")
        fp.write(f"#define MESH_L2_NUM_PARTITIONS {NUM_PARTITIONS}U\n")
        fp.write(f"#define MESH_L2_PARTITION_SIZE_BYTES {PARTITION_SIZE_BYTES}U\n")
        fp.write(f"#define MESH_L2_PARTITION_SPAN_BYTES {span}U\n")
        fp.write(f"#define MESH_L2_FLOATS_PER_PARTITION {nfloats}U\n")
        fp.write(f"#define MESH_L2_NUM_GRANULES {ngran}U\n")
        fp.write(f"#define MESH_L2_FLOATS_PER_GRANULE {FLOATS_PER_GRANULE}U\n")
        fp.write(f"#define MESH_L2_GRANULE_STRIDE_BYTES {GRANULE_STRIDE_BYTES}U\n")
        fp.write(f"#define MESH_L2_REMOTE_ACCESS_STRIDE {REMOTE_ACCESS_STRIDE}U\n")
        fp.write(f"#define MESH_L2_BANK_SELECT_BIT_START {bank_start}U\n")
        fp.write(f"#define MESH_L2_BANK_SELECT_BIT_END {bank_end}U\n\n")

        fp.write(
            "static inline uint64_t mesh_l2_elem_byte_offset(uint32_t elem_index) {\n"
            "  const uint32_t g = elem_index >> 4;\n"
            "  const uint32_t f = elem_index & 15u;\n"
            f"  return (uint64_t)g * {GRANULE_STRIDE_BYTES}u + (uint64_t)f * 4u;\n"
            "}\n\n"
        )

        _emit_u64_array(fp, "mesh_l2_partition_base", partition_base_addrs)
        _emit_u32_array(fp, "mesh_l2_partition_home_core", partition_home_core)
        _emit_u32_array(fp, "mesh_l2_partition_home_bank", partition_home_bank)
        _emit_u32_array(fp, "mesh_l2_partition_remote_core", partition_remote_core)

        fp.write("#endif /* MESH_L2_DATA_H */\n")


def manhattan_hops(src_core: int, dst_bank: int, width: int = 2) -> int:
    sx, sy = src_core % width, src_core // width
    dx, dy = dst_bank % width, dst_bank // width
    return abs(sx - dx) + abs(sy - dy)


def analyze_access_pattern() -> None:
    """Print expected L2 bank-select hop mix for mesh_l2_affinity (analytic model)."""
    bank_start, _ = bank_select_bits(
        cache_size=1048576,
        line_size=64,
        word_size=64,
        num_ways=8,
        num_banks=4,
    )
    nfloats = floats_per_partition()
    n_remote = nfloats // REMOTE_ACCESS_STRIDE
    reps = 4
    parts = NUM_PARTITIONS
    bases = [partition_base(i, bank_start, i) for i in range(parts)]
    home_bank = lambda part: part

    def phase_hops(exec_core: int, part: int) -> tuple[int, int, int]:
        home_b = home_bank(part)
        remote_b = (part + 2) % NUM_PARTITIONS
        h0 = h1 = h2 = 0

        def add_hop(h: int) -> None:
            nonlocal h0, h1, h2
            if h == 0:
                h0 += 1
            elif h == 1:
                h1 += 1
            else:
                h2 += 1

        for _i in range(nfloats):
            for bank in (home_b, home_b):
                add_hop(manhattan_hops(exec_core, bank))
        for i in range(0, nfloats, REMOTE_ACCESS_STRIDE):
            add_hop(manhattan_hops(exec_core, remote_b))
        return h0, h1, h2

    modes = {
        "HOME": lambda p: p,
        "REMOTE": lambda p: (p + 2) % NUM_PARTITIONS,
        "ANY(all_core0)": lambda _p: 0,
    }
    print("=== mesh_l2_affinity analytic L2 hop model (per child, 1 rep) ===")
    print(f"  floats/partition={nfloats} remote_touches={n_remote} stride={REMOTE_ACCESS_STRIDE}")
    print(f"  bank-confined: {FLOATS_PER_GRANULE} floats / {GRANULE_STRIDE_BYTES}B granule\n")
    for name, core_fn in modes.items():
        t0 = t1 = t2 = 0
        for p in range(parts):
            a, b, c = phase_hops(core_fn(p), p)
            t0 += a
            t1 += b
            t2 += c
        tot = t0 + t1 + t2
        scale = reps * parts
        print(f"{name} x {scale} launches:")
        print(f"  0-hop (close): {t0 * scale}  ({100.0 * t0 / tot:.1f}% per launch)")
        print(f"  1-hop (mid):   {t1 * scale}  ({100.0 * t1 / tot:.1f}%)")
        print(f"  2-hop (far):   {t2 * scale}  ({100.0 * t2 / tot:.1f}%)")
        print(f"  total addrs:   {tot * scale}\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-o",
        "--output",
        default="mesh_l2_data.h",
        help="Output C header path (default: ./mesh_l2_data.h)",
    )
    parser.add_argument(
        "--analyze",
        action="store_true",
        help="Print expected close/mid/far L2 hop counts for HOME/REMOTE/ANY",
    )
    args = parser.parse_args()
    if args.analyze:
        analyze_access_pattern()
        return
    out = os.path.abspath(args.output)
    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    write_header(out)
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
